NBlood/NBlood

.gitignore

Built Debug/Release configurations and excluded all untracked files
Fixed mix of Windows/UNIX line endings

Update .gitignore with entries for MSVC and Xcode

---

source/blood/src/db.cpp
source/blood/src/demo.cpp
source/blood/src/eventq.cpp
source/blood/src/resource.cpp
source/blood/src/tile.cpp
source/blood/src/trig.cpp
source/blood/src/view.cpp

Tested on big endian Linux. Currently the Post Mortem demo desyncs, but I plan to investigate it later.

Big endian fixes

---

source/blood/src/aiboneel.cpp

workaround for bone eel attack state

---

source/build/src/voxmodel.cpp

Fix VBO binding when loading voxels

---

source/blood/src/actor.cpp
source/blood/src/actor.h
source/blood/src/blood.cpp
source/blood/src/blood.h
source/blood/src/eventq.h
source/blood/src/triggers.cpp
source/blood/src/triggers.h
source/blood/src/warp.cpp

V Effect spawner
V SEQ Spawner
V Wind Generator
V Data Changer
V FX Wave Changer
V RandomTX
V Sequential TX
V Sprite Damager

Ported GDX features (New types):

---

platform/Windows/include/SDL2/SDL_hints.h
platform/Windows/include/dx/dsound.h
platform/Windows/nblood.vcxproj
platform/Windows/nblood.vcxproj.filters
source/blood/src/AIUNICULT.cpp
source/blood/src/AIUNICULT.h
source/blood/src/actor.cpp
source/blood/src/actor.h
source/blood/src/ai.cpp
source/blood/src/aiburn.cpp
source/blood/src/aiburn.h
source/blood/src/aicult.cpp
source/blood/src/blood.h
source/blood/src/db.cpp
source/blood/src/db.h
source/blood/src/dude.cpp
source/blood/src/player.cpp
source/blood/src/triggers.cpp
source/blood/src/view.cpp

GDX Features:
- Ported Custom Dude (Type 254).
-------------
- Fixed potential bugs with custom palettes for water.
- Renamed palette to medium in XSPRITE structure.

Merger request

---

source/blood/src/actor.cpp
source/blood/src/actor.h
source/blood/src/aiunicult.cpp
source/blood/src/aiunicult.h
source/blood/src/triggers.cpp
source/blood/src/triggers.h

- Ported Custom Dude Spawn from GDX
- Performance fixes for Dude Target Changer
- Various fixes for Custom Dude, include crash fix with Life Leech

New GDX Features and fixes

---

source/blood/src/actor.cpp
source/blood/src/aiunicult.cpp
source/blood/src/aiunicult.h
source/blood/src/sfx.cpp
source/blood/src/sfx.h
source/blood/src/triggers.cpp
source/build/src/palette.cpp

- Fixes for SequentialTX and Custom Dude types
- Minor changes.

Various bug fixes

---

platform/Apple/EDuke32.xcodeproj/project.pbxproj

`aiunicult.cpp` and `aiunicult.h` were missing from Xcode project

Fix building via Xcode project

---

Common.mak
source/build/src/lz4.c

Supporting newer version of lz4 after their refactoring.

BSD build fix.

---

source/blood/src/actor.cpp
source/blood/src/ai.cpp
source/blood/src/aiunicult.cpp
source/blood/src/aiunicult.h
source/blood/src/triggers.cpp

Few fixes and additions to previous commit.

---

Common.mak
source/blood/src/gamemenu.cpp

detect SSE2 on BSD too

---

.gitignore
source/blood/src/blood.cpp

Related issue: https://github.com/nukeykt/NBlood/issues/136

fix endgame credits listing

---

source/blood/src/actor.cpp
source/blood/src/view.cpp

Took me 5 days :'(
Thank you C.
Related issue: https://github.com/nukeykt/NBlood/issues/137

extra can be -1 then pointer will point to random

---

source/blood/src/actor.cpp
source/blood/src/ai.cpp
source/blood/src/aiunicult.cpp
source/blood/src/aiunicult.h
source/blood/src/common_game.h
source/blood/src/triggers.cpp

- Incarnation fix for custom dude
- gSpriteMass fix
- "concuss sprite" modern type (WIP)

Fixes and updates for previous commit

---

source/blood/src/barf.cpp
source/blood/src/resource.cpp

- replaced stricmp with strcasecmp and strncasecmp
https://linux.die.net/man/3/strcasecmp
- replaced all Microsoft specific types with standard ones
- replaced all instances of MAX_PATH with BMAX_PATH

Fix Linux compilation

---

source/blood/src/actor.cpp
source/blood/src/common_game.h
source/blood/src/endgame.cpp
source/blood/src/player.cpp
source/blood/src/triggers.cpp

- Fixes for refactor (wrong kills count)
- Fixes for refactor (proximity flag for dudes)
- Fixes for refactor (invisibility pickup was not working)

Fixes for refactor

---

source/blood/src/actor.cpp
source/blood/src/actor.h
source/blood/src/blood.cpp
source/blood/src/callback.cpp
source/blood/src/callback.h
source/blood/src/common_game.h
source/blood/src/db.cpp
source/blood/src/db.h
source/blood/src/eventq.cpp
source/blood/src/eventq.h
source/blood/src/messages.cpp
source/blood/src/player.cpp
source/blood/src/player.h
source/blood/src/sectorfx.cpp
source/blood/src/sound.cpp
source/blood/src/triggers.cpp
source/blood/src/triggers.h
source/blood/src/view.cpp
source/blood/src/weapon.cpp
source/blood/src/weapon.h

- Added QAV scene player (playing user animation instead of weapon)
- Added trigger event intiator for sprites (WIP and experimental)

Refactor: xsector, xwall and xsprite structs

---

source/exhumed/src/enginesubs.cpp
source/exhumed/src/trigdat.cpp

Some minor changes to fix the build on OpenBSD with libc++.

PCExhumed build fixes

---

source/exhumed/src/exhumed.cpp
source/exhumed/src/runlist.h
source/exhumed/src/sequence.cpp

Tested under big endian Linux, everything appears to be functional.

PCExhumed: big endian fix

---

source/build/src/polymost.cpp

I think this should be needed, but I'm not sure.

take maphacks into consideration

---

source/blood/src/blood.cpp
source/blood/src/player.cpp
source/blood/src/player.h

Fixes https://github.com/nukeykt/NBlood/issues/308
Please squash on merge so the amend commits won't pollute the main branch history.

Blood: Clear keys on new level, fixes #308

---

source/blood/src/ai.cpp
source/blood/src/aiunicult.cpp
source/blood/src/nnexts.cpp
source/blood/src/nnexts.h

Blood: Rename Ummune to Immune

---

source/build/src/voxmodel.cpp

Fix VBO setup for voxels

---

source/blood/src/triggers.cpp

Blood: FIX Caleb sounds multiplayer

---

source/blood/src/blood.cpp

Blood: duplicated INI files in startup window fix #323

Blood: Fix duplicated INI files in startup window

---

source/blood/src/actor.cpp

fixes https://github.com/nukeykt/NBlood/issues/337

Blood: fix ILLUSION.MAP crash

---

source/blood/src/blood.cpp

Blood: MoveFolder+Addons texture count fix

---

source/rr/src/actors.cpp
source/rr/src/player.cpp

The camera not following the actor who whacked you is the main one here.

Backports of EDuke32 fixes for RedNukem

---

source/blood/src/view.cpp
source/build/src/palette.cpp

It's that time of the year again when I build NBlood without Polymost.

Fix the USE_OPENGL=0 build

---

source/blood/src/nnexts.cpp

- kModernEffectGen: fix getting middle of the sprite

- Disable STD random for autobuilds

---

source/blood/src/menu.cpp

bugfix for: `single episode addons are overlapping with the new user map selection`

Blood: fix episode selection

---

source/rr/src/gameexec.cpp
source/rr/src/menus.cpp
source/rr/src/n64/reality.cpp
source/rr/src/n64/reality.h
source/rr/src/n64/reality_render.cpp

Fixes https://github.com/nukeykt/NBlood/issues/398

Rednukem: fix building with USE_OPENGL=0

---

source/blood/src/osdcmd.cpp
source/build/src/sdlayer.cpp

Blood: r_upscalefactor related fixes

---

source/blood/src/db.h
source/blood/src/player.cpp

Blood: Use kMaxXSectors instead of magic number

---

source/blood/src/controls.cpp

Fixes https://github.com/nukeykt/NBlood/issues/416

Blood: Fix moving the 2d map on the Y axis when follow mode is turned off

---

source/blood/src/view.cpp

Closes https://github.com/nukeykt/NBlood/issues/417
That annoying blood droplet is from the menu...

Blood: Add asbestos armor and other power-ups to power-up displayer

---

source/exhumed/src/exhumed.cpp
source/exhumed/src/memorystream.cpp
source/exhumed/src/menu.cpp

This PR fixes the BOOK.MOV and demo playback on big endian systems.

PCExhumed: more big endian fixes

---

source/exhumed/src/exhumed.cpp
source/exhumed/src/grpscan.cpp
source/exhumed/src/menu.cpp
source/exhumed/src/menu.h
source/exhumed/src/osdcmds.cpp

This PR adds support for the Exhumed Demo. Closes #446

PCExhumed: Exhumed Demo support

---

source/witchaven/src/common_game.h
source/witchaven/src/input.cpp
source/witchaven/src/witchaven.cpp

Replaced some magic numbers, replaced some of the integers with booleans, removed other games from searchpathtypes

EWitchaven: minor code cleanup

---

source/exhumed/src/exhumed.cpp
source/exhumed/src/menu.cpp

I added byteswaps to menu_DemoGameSave where necessary, and also fixed a mistake I previously made in WritePlaybackInputs.

PCExhumed: Demo recording big endian fix

---

source/exhumed/src/exhumed.h
source/exhumed/src/grenade.cpp
source/exhumed/src/gun.cpp
source/exhumed/src/menu.cpp
source/exhumed/src/move.cpp
source/exhumed/src/move.h
source/exhumed/src/player.cpp
source/exhumed/src/player.h
source/exhumed/src/switch.cpp
source/exhumed/src/wasp.cpp

This PR gives human readable names to a few struct fields.

PCExhumed: Give some struct fields human readable names

---

source/blood/src/credits.cpp

Fixes https://github.com/nukeykt/NBlood/issues/476

Blood: search for the credit videos in the movie folder too

---

source/blood/src/view.cpp

fix variable when NOONE_EXTENSIONS is defined.

Fix variable

---

source/blood/src/nnexts.cpp
source/blood/src/nnexts.h

Add power up control for kModernPlayerControl

Fix max players range check for kModernPlayerControl

---

source/blood/src/aispid.cpp
source/blood/src/aispid.h
source/blood/src/callback.cpp
source/blood/src/fx.cpp
source/blood/src/fx.h
source/blood/src/weapon.cpp

This PR renames the various untitled functions/variables for AI spider class.

[Blood] Renamed untitled spider functions

---

source/blood/src/actor.cpp
source/blood/src/aibeast.cpp
source/blood/src/aicaleb.cpp
source/blood/src/aicerber.cpp
source/blood/src/aicult.cpp
source/blood/src/aigarg.cpp
source/blood/src/aighost.cpp
source/blood/src/aigilbst.cpp
source/blood/src/aitchern.cpp
source/blood/src/aiunicult.cpp
source/blood/src/common_game.h
source/blood/src/gameutil.cpp
source/blood/src/map2d.cpp
source/blood/src/nnexts.cpp
source/blood/src/player.cpp
source/blood/src/triggers.cpp
source/blood/src/view.cpp
source/blood/src/weapon.cpp

This can help on older platforms where the fixed shift variants are slightly faster. I verified with the original demos that everything still works.

NBlood: replace mulscale, dmulscale, divscale with their fixed shift variants

---

source/blood/src/actor.cpp
source/blood/src/ai.cpp
source/blood/src/ai.h
source/blood/src/aicult.cpp
source/blood/src/aipod.cpp
source/blood/src/aiunicult.cpp
source/blood/src/blood.cpp
source/blood/src/demo.cpp
source/blood/src/demo.h
source/blood/src/fx.cpp
source/blood/src/fx.h
source/blood/src/loadsave.cpp
source/blood/src/menu.cpp
source/blood/src/messages.cpp
source/blood/src/messages.h

This rename sub_5BCF4() to ResetCheats(), and sub_746D4() to fxSpawnBloodPod(). It also renames CDemo's at59ef to nDemosFound.

Blood: Rename various functions

---

source/blood/src/controls.cpp
source/blood/src/messages.cpp
source/blood/src/nnexts.cpp
source/blood/src/player.cpp
source/blood/src/triggers.cpp
source/blood/src/view.cpp
source/blood/src/weapon.cpp

This PR replaces a few missed lines not covered by commit https://github.com/nukeykt/NBlood/commit/7e27d153fc61be73c7f2aa1d364deaf48f09314d.

Blood: Replace various weapon IDs with enum

---

source/blood/src/aizomba.cpp
source/blood/src/gameutil.cpp
source/blood/src/mirrors.cpp

This PR updates a number of missing extended sprite range masks that were missed for commit https://github.com/nukeykt/NBlood/commit/519f3d75f1f1a1274ac08b9a30d5f99e16f77db1.

Blood: Update non-extended sprite range masks in gameutil.cpp

---

source/blood/src/actor.cpp
source/blood/src/aicult.cpp
source/blood/src/aiunicult.cpp
source/blood/src/callback.cpp
source/blood/src/db.h
source/blood/src/eventq.cpp
source/blood/src/eventq.h
source/blood/src/nnexts.cpp
source/blood/src/nnexts.h
source/blood/src/player.cpp
source/blood/src/triggers.cpp
source/blood/src/triggers.h
source/blood/src/weapon.cpp

gModernMap:
- The return of the event causer (kChannelEventCauser, TXID 50).
- Fix flags for kModernPropertiesChanger type.
- Add new modern type kModernVelocityChanger.
- New features for kMarkerWarpDest type.
- New features for kModernSectorFXChanger type.
- Fix sector condition 58.
- Fix sprite hitscan conditions (35 - 38).
- Add new command (kCmdEventKillFull).
- Misc changes.

- Change gBusyCount limit to a higher value since xsector limit raised.

---

source/blood/src/actor.cpp
source/blood/src/common_game.h
source/blood/src/nnexts.h
source/blood/src/triggers.cpp

This PR restores the ability to build without NOONE_EXTENSIONS.

Blood: fix building without NOONE_EXTENSIONS

---

source/blood/src/blood.cpp
source/blood/src/network.cpp
source/blood/src/player.cpp

This replaces a few magic number variables with the tick rate constants

Blood: Use tick constants

---

source/blood/src/actor.cpp
source/blood/src/player.cpp

This PR replaces a few magic numbers with posture constraint enums.

Blood: Use posture constant enums

---

source/blood/src/asound.cpp

This PR fixes the issue described here https://github.com/nukeykt/NBlood/issues/612

Blood: Fix incorrect ambient vol clipping channel

---

source/blood/src/actor.cpp
source/blood/src/aispid.cpp
source/blood/src/barf.cpp
source/blood/src/blood.cpp
source/blood/src/db.cpp
source/blood/src/db.h
source/blood/src/fx.cpp
source/blood/src/gameutil.cpp
source/blood/src/gameutil.h
source/blood/src/gui.cpp
source/blood/src/menu.cpp
source/blood/src/misc.cpp
source/blood/src/network.cpp
source/blood/src/network.h
source/blood/src/player.cpp
source/blood/src/player.h
source/blood/src/sectorfx.cpp
source/blood/src/startosx.game.mm
source/blood/src/view.cpp
source/blood/src/warp.cpp
source/blood/src/warp.h

This PR is a collection of smaller commits that range from basic renames to removing unused variables often given by GCC/Zig.

Blood: Misc clean up

---

source/blood/src/blood.cpp
source/blood/src/choke.cpp
source/blood/src/choke.h
source/blood/src/player.cpp
source/blood/src/player.h
source/blood/src/view.cpp

This PR document the choking hand class as well as each of the members. It also moves the choke callback function to player.cpp.

Blood: Document choke class

---

source/blood/src/actor.cpp
source/blood/src/aihand.cpp
source/blood/src/blood.cpp
source/blood/src/callback.cpp
source/blood/src/common_game.h
source/blood/src/endgame.cpp
source/blood/src/fx.cpp
source/blood/src/gib.cpp
source/blood/src/levels.cpp
source/blood/src/map2d.cpp
source/blood/src/menu.cpp
source/blood/src/messages.cpp
source/blood/src/network.cpp
source/blood/src/nnexts.cpp
source/blood/src/player.cpp
source/blood/src/player.h
source/blood/src/triggers.cpp
source/blood/src/view.cpp
source/blood/src/warp.cpp
source/blood/src/weapon.cpp

This PR replaces the constant numbers with friendlier names for level struct nGameType/uGameFlags members.

Blood: Use kGameType/kGameFlag constants for nGameType/uGameFlags

---

source/build/src/baselayer.cpp

I'm not sure if this would be too verbose but it could probably help people file bug reports or diagnose any issues
https://github.com/nukeykt/NBlood/issues/610

initprintf also log to nblood.log (issue #610)

---

GNUmakefile
platform/Windows/nblood.vcxproj
platform/Windows/nblood.vcxproj.filters
source/blood/src/actor.h
source/blood/src/aiunicult.cpp
source/blood/src/db.cpp
source/blood/src/db.h
source/blood/src/eventq.h
source/blood/src/nnexts.cpp
source/blood/src/nnexts.h
source/blood/src/nnextsif.cpp
source/blood/src/nnextsif.h
source/blood/src/player.cpp
source/blood/src/sfx.h
source/build/src/osd.cpp

- New features revision
- Fix multiplayer desync for kModernDudeCustom
- Fix multiplayer desync for patrolling AI
- Kill callbacks for kModernEffectGen
- Rewrite kModernCondition code and put it in new file
OSD:
- Fix asan error

gModernMap

---

source/blood/src/actor.cpp
source/blood/src/nnexts.cpp
source/blood/src/nnexts.h
source/blood/src/nnextsif.cpp

- Use dynamic "super xsprites" lists
- Remove undocumented vertical wind for kModernWindGen
- Fix unsafe floor sprite detection for kModernSlopeChanger
- Update kModernSectorFXChanger
- Update Gib/Explode object
- Update Blood and Water drips

gModernMap:

---

source/blood/src/nnexts.cpp
source/blood/src/nnextsif.cpp
source/blood/src/nnextsif.h

- Remove _fastcalls

---

source/blood/src/actor.cpp
source/blood/src/ai.cpp
source/blood/src/aibeast.cpp
source/blood/src/blood.cpp
source/blood/src/gameutil.cpp
source/blood/src/m32common.cpp
source/blood/src/m32exec.cpp
source/blood/src/m32vars.cpp
source/blood/src/map2d.cpp
source/blood/src/map2d.h
source/blood/src/mapedit.cpp
source/blood/src/menu.cpp
source/blood/src/tile.cpp
source/blood/src/tile.h
source/blood/src/view.cpp
source/blood/src/weapon.cpp

This is a collection of tweaks/fixes for Blood. They include fixing vsync so it applies during initialization, documenting CViewMap class, and fixing the selected fps setting in the menu for 144hz displays.

Blood: Various tweaks

---

source/blood/src/demo.cpp
source/blood/src/player.cpp
source/blood/src/view.cpp

Fixes https://github.com/nukeykt/NBlood/issues/683

Blood: Fix demo playback support

---

.github/workflows/build.yml
.github/workflows/publish.yml

This way it is possible for everyone to bisect regressions.

keep old releases after publishing to GitHub

---

source/blood/src/blood.cpp

NotBlood did this already, but... consistency doesn't hurt, right? If you turn down adding a name for Death Wish, I won't complain at all...

Capitalized the P in "Passage", and optional DW.ini desc

---

source/audiolib/src/tsf.h

This PR imports the latest commits from schellingb/TinySoundFont, it **has not been tested extensively** but appears to work fine.

Updated TinySoundFont library

---

source/blood/src/menu.cpp

This PR exposes the KMT vsync options in the menu for Windows targets.

Blood: Expose KMT option for vsync

---

source/blood/src/view.cpp

This PR reduces the number of loops computed within viewDrawPowerUps() by presorting the currently available powerups.

Blood: Optimized viewDrawPowerUps()

---

source/blood/src/menu.cpp

Addresses issues #702 and (partly) #781

Blood: Allow mouse axis sensitivity to be set to zero

---

source/blood/src/actor.cpp
source/blood/src/blood.cpp
source/blood/src/common_game.h
source/blood/src/demo.cpp
source/blood/src/levels.cpp
source/blood/src/levels.h
source/blood/src/menu.cpp
source/blood/src/messages.cpp
source/blood/src/network.cpp

This PR incorporates BloodGDX style custom difficulty.

Blood: Add custom difficulty feature

---

source/blood/src/screen.cpp

This PR fixes the issue described at https://github.com/nukeykt/NBlood/issues/781

Blood: Apply gUpscaleFactor on init

---

source/blood/src/messages.cpp

This improve the robustness for clearing out messages when switching from non-vanilla mode to vanilla mode

Blood: Fix issue introduced in 961a063957ca2b9b73db88adf6847f7ffc805253

---

source/blood/src/view.cpp

This PR optimizes the check used for setting third person sprite for improved multiplayer prediction.

Blood: Optimize 76c00bf0debcc72fbc639f15a8679fddf7282f4a

---

source/build/src/sdlayer.cpp

This PR fixes rumble detection for controllers with EDuke32.
Fixes #750

Fix rumble detection

---

source/blood/src/menu.cpp

This PR removes some legacy code relating to fps offset, which has since been removed.

Blood: Remove unused fps offset code

---

source/blood/src/menu.cpp

This PR fixes loading saves when using a separate game mod path.
Fixes #771

Blood: Fix loading when using a separate game mod path

---

source/blood/src/_functio.h
source/blood/src/menu.cpp
source/blood/src/view.cpp

These are a few misc tweaks for NBlood.

Blood: Misc fixes

---

source/blood/src/osdcmd.cpp

This PR fixes an issue introduced in commit 843ab4789967ce1764349ca57cd46bf149c5b763
Fixes #858

Blood: Update hud_stats CVAR range

---

source/blood/src/view.cpp

This PR fixes modern demo playback interpolation

Blood: Fix demo playback for non-legacy demos

---

source/rr/src/common.cpp

Added check in Windows version for installation of GOG version of WWII GI.

Rednukem: Added GOG version of WWII GI
