NBlood/NBlood

- .appveyor.yml
- .travis.yml
Closes #3 
Please sign-in to [AppVeyor](https://www.appveyor.com) and [Travis](https://travis-ci.org) with your GitHub account. There you can enable CIs for your repositories.
Check build status of my fork [here](https://ci.appveyor.com/project/alexey-lysiuk/nblood/builds/22392594) and [here](https://travis-ci.org/alexey-lysiuk/NBlood/builds/493646356). As you can see, there are some issues ready to fix 😉 I'll take a look at macOS, most likely Linux will be fixed as well.
> Add AppVeyor and Travis CIs

- source/build/src/compat.cpp
On macOS sysconf(_SC_PAGE_SIZE) returns 4096 and sysconf(_SC_PHYS_PAGES) returns 4'194'304
scpagesiz * scphyspages is equal to 0x4'0000'0000 which becomes zero after casting to 32-bit unsigned integer
This leads to 'BUFFER TOO BIG TO FIT IN CACHE!' fatal error on startup
> Fix integer overflow when determine system memory size

- platform/Windows/eduke32.vcxproj
- platform/Windows/mapster32.vcxproj
This fixes 32-bit Windows builds
Continuous integration builds are finally green
> Remove references to missing .manifest files

- source/build/include/sdlayer.h
Some common resolutions (e.g. 1280x1024) are discarded because of the aspect ratio. This simple patch enable them.
> Enable more resolutions

- .travis.yml
Apparently, `luajit` isn't used at the moment, it was added by mistake.
> Remove luajit from dependencies in Travis configuration

- source/blood/src/tile.cpp
when compiling without OpenGL tileProcessGLVoxels is called yet never defined nor declared
> fix compiling without opengl

- source/build/src/engine.cpp
without USE_OPENGL polymost_spriteHadTranslucency  is never declared nor defined
this PR adds preprocessor directives to get around that
> fix invalid function call

- source/blood/src/triggers.cpp
both of those cases initialize something and because of how switch cases work they are in scope to all other cases but never initialized causing a compilation error (atleast it does on gcc 8.3.1)
> add scope to cases that initialize something

- source/blood/src/actor.cpp
- source/blood/src/ai.cpp
- source/blood/src/aiunicult.cpp
- source/blood/src/db.cpp
- source/blood/src/db.h
- source/blood/src/triggers.cpp
- Quick fix for Cerberus AI, so it can normally move in E3M7-like maps
- Rename in XSECTOR structure (damageType)
- Fix for dudes that inherit properties of spawner from wrong type of source.
- Minor changes
> Various fixes

- source/blood/src/getopt.cpp
It was impossible to use the -game_dir option, or use absolute paths on Unix due to confusion with Windows "/" switch character.
I think there are still a few quirks in the options handling to resolve, but this should get rid of a few of the bigger ones.
> GetOptions fixes

- source/blood/src/tile.cpp
While working on my RISC OS port I spotted that there was a lot of stuttering, especially when firing weapons. Some debugging revealed that it was because tileLoadTile wasn't checking to see if the tile was already loaded before calling tileLoad.
> Fix tileLoadTile to check if tile already loaded

- source/blood/src/actor.cpp
- source/blood/src/actor.h
- source/blood/src/ai.cpp
- source/blood/src/aiunicult.cpp
- source/blood/src/aiunicult.h
- source/blood/src/blood.cpp
- source/blood/src/blood.h
- source/blood/src/callback.cpp
- source/blood/src/db.cpp
- source/blood/src/db.h
- source/blood/src/dude.cpp
- source/blood/src/dude.h
- source/blood/src/eventq.cpp
- source/blood/src/eventq.h
- source/blood/src/player.cpp
- source/blood/src/player.h
- source/blood/src/seq.cpp
- source/blood/src/seq.h
- source/blood/src/sfx.cpp
- source/blood/src/sfx.h
- source/blood/src/triggers.cpp
- source/blood/src/triggers.h
Seq Spawner should can spawn seq on TX ID sprite
FX Effect Gen should can spawn effect on TX ID sprite
Dudelockout for Proximity
Sight flag (just for player)
Touch flag for any type
Dudelockout for Touch
Data accumulator type (as generator)
Force OFF Data accumulator type after goal value reached for all objects
Remove previously dropped items from random item generators if it was not picked up.
Wind Generator should can create wind on current sector, if TX ID is empty
The wind should stop after wind gen is off
Free data4 for wind gen
Custom dude: Count mass according sprite ((sprite size + repeats) * clipdist) / 25
Custom dude: Recoil chance according mass and weaponType
Custom dude: Stomp target if sprite is too small
Custom dude: Custom clipdist for (affects mass also)
Custom dude: …
>  Porting modern features for mappers from GDX

- source/blood/src/db.cpp
- source/blood/src/gui.cpp
- source/blood/src/gui.h
- source/blood/src/startgtk.game.cpp
- source/blood/src/startosx.game.mm
Various things in the code did not allow for compilation under Linux
I think this PR resolves that
Changes:
- _MAX_PATH defines as PATH_MAX
- Window renamed to Win, the X header already typedefs Window as an XID
- replace itoa with snprintf, should give the same results
This PR needs to be tested with MSVC to ensure nothing broke on the Windows side
> Fix linux compilation

- .gitignore
- source/blood/src/blood.cpp
- source/blood/src/config.cpp
- source/blood/src/osdcmd.cpp
- source/blood/src/view.cpp
- source/blood/src/view.h
Currently the crosshair looks different in NBlood than in the original game. In the original it consists of multiple colors like the corresponding tile but in NBlood it is just one color. It is because NBlood is recoloring the crosshair by the "crosshaircolor" console feature, although nothing is asking for it.
I kept the possibility to change the color of the crosshair from the console or config file. I also added the "crosshairreset" console command if somebody wants to restore the original crosshair, so it is not needed to quit the game, edit the config file (by deleting the crosshaircolor setting) and restart the game.
> Fix the crosshair

- Common.mak
In the make file a few lines above it sets the architecture to Pentium 3 and then later it adds the SSE2 instruction set optimizations. Pentium 3 doesn't have SSE2, nor any 32 bit AMD CPU. Only Pentium 4 has it. It caused Illegal instruction crash for me on my AMD Athlon XP.
The problematic line was at source/build/src/osd.cpp:90
It wants to assign a double value and the compiler generated SSE2 code, only SSE2 has double float operators, which the Pentium 3 doesn't have.
> fix Illegal instruction crash on 32 bit AMD processors and Intel Pentium 3

- source/blood/src/resource.cpp
- source/build/include/build.h
Fixed the byte swapping for the extended SEQFRAME structure and moved some voxel declarations out of the USE_OPENGL block.
> Build fix for big endian and USE_OPENGL=0

- source/blood/src/common.cpp
the Linux build of NBlood had not added Fresh Supply or One Unit Whole Blood to the search path so I added them
> add steam versions to search path

- source/build/src/compat.cpp
Changed a cast in Bgetsysmemsize() from uint32_t to size_t. If size_t is 64-bit and the system has more than 4 GB of memory then this casting it to uint32_t can result in a bogus value (e.g. 0 on macOS).
> Bgetsysmemsize 64-bit fix

- source/blood/src/resource.cpp
Not doing so will cause problems for example when custom SEQs are defined in blood.def and then loading custom maps. When loading custom maps, the custom map will be removed from the resource dictionary (and then re-inserted), after removing a node a reindex operation happens but that was not reindexing the external resources, therefore custom SEQs stopped working.
> Reindex external resources too

- source/build/include/palette.h
- source/build/src/mutex.cpp
- source/build/src/palette.cpp
- source/build/src/sdlayer.cpp
- source/exhumed/src/exhumed.cpp
- source/exhumed/src/light.cpp
- source/exhumed/src/movie.cpp
- source/exhumed/src/sequence.cpp
Building with SDL 1.2 and without OpenGL was broken in Exhumed. Some of the fixes are inside Build and could apply to other games.
> Fix the SDL 1.2 and USE_OPENGL=0 build

- source/blood/src/view.cpp
This is useful when the voxel pack is used, without this patch, sprites with `notmd` defined would be higher than they should.
> Blood: Fix sprite positions when notmd is defined in maphack file

- source/blood/src/loadsave.cpp
Related issue: https://github.com/nukeykt/NBlood/issues/277
> Blood: stop music after loading a game with a map without music

- source/blood/src/menu.cpp
Fixes: https://github.com/nukeykt/NBlood/issues/282
There is only OpenGL implementation for v-sync in the game, so just hide this option.
I'm using the same approach as few lines above, the renderer selection is also missing in non-opengl builds.
> Blood: don't show vsync menu option in non-opengl builds fixes #282

- source/blood/src/aiunicult.cpp
- source/blood/src/triggers.cpp
Remove some fallthrough annotations so clang does not fatally error:
source/blood/src/aiunicult.cpp:1983:13: error: fallthrough annotation does not
directly precede switch label
source/blood/src/triggers.cpp:1045:33: error: fallthrough annotation does not
directly precede switch label
> Blood: change fallthrough annotations to fix clang build

- source/rr/src/game.cpp
- source/rr/src/net.h
A few Redneck Rampage specific Net_* functions weren't stubbed out, and the ingame input was broken as it was only handled in Net_GetInput.
> Rednukem: fix building with NETCODE_DISABLE

- Common.mak
- platform/Windows/nblood.vcxproj
- source/blood/src/common_game.h
This way Visual Studio can properly colorize the source code.
Also, it is possible to turn it on/off when building, no source code modification is required.
> Blood: proper use of the NOONE_EXTENSIONS preprocessor definition

- source/blood/src/menu.cpp
Saving happens so quick, that the user cannot see that anything happened at all or not. The loading screen is not even visible sometimes.
> Blood: show "game saved" message

- source/rr/src/gameexec.cpp
Original DN3D code looks like this:
case 88:
insptr++;
ps[g_p].actors_killed += *insptr;
hittype[g_i].actorstayput = -1;
insptr++;
break;
> RedNukem: fix broken kill counter for non-Redneck games.

- source/blood/src/credits.cpp
Cinematics still can be skipped instantly by pressing Escape. But pressing any other button will have effect only after 2 seconds.
In the original game it is only possible to skip the video with the `Escape` key.
Fixes https://github.com/nukeykt/NBlood/issues/285
> Blood: Prevent accidental skipping of cinematics

- source/blood/src/blood.cpp
- source/blood/src/gamemenu.cpp
- source/blood/src/gamemenu.h
- source/blood/src/levels.h
- source/blood/src/menu.cpp
Currently the users are only able to play custom maps (if they don't have an .ini file) by entering commands into the console. Selecting the difficulty is not possible this way, the previously used difficulty will be used (by default Lightly Broiled). This is not really intuitive for users.
Fixes #202
> Blood: Add User Map menu to episode select

- source/blood/src/gamemenu.cpp
Since `sf2bankfile` and `gGameOptions.szUserMap` is using `BMAX_PATH` too (and everything else).
> Blood: Use BMAX_PATH instead of MAX_PATH in CGameMenuFileSelect

- source/blood/src/menu.cpp
- source/blood/src/network.h
Now we can use this new cool file selector in the start new multiplayer game menu too to select the user map instead of typing its name.
> Blood: Add user map selector menu for multiplayer too

- source/exhumed/src/engine.h
Error when building with `USE_OPENGL=0`:
```
source/exhumed/src/gun.cpp:309:67: error: ‘OSD_Printf’ was not declared in this scope
OSD_Printf("%s %d: overflow\n", EDUKE32_FUNCTION, __LINE__);
^
Failed building obj/exhumed/gun.o from source/exhumed/src/gun.cpp!
GNUmakefile:1495: recipe for target 'obj/exhumed/gun.o' failed
make: *** [obj/exhumed/gun.o] Error 1
```
Maybe the include is not placed into the perfect place, but it solves the issue. I'm not familiar with the codebase.
Fixes #395
> Exhumed: fix USE_OPENGL=0 build

- source/blood/src/endgame.cpp
- source/blood/src/endgame.h
- source/blood/src/view.cpp
Don't add super secrets to the counter. This way the same numbers are shown in the level stats like at the end level screen.
Fixes #403
> Blood: Fix found secrets count in level stats displayer

- source/exhumed/src/view.cpp
This PR fixes the bouncy torches on level 5, and possibly many others. I ported this from PowerSlaveGDX.
> PCExhumed: Torch bouncing fix

- README.md
The readme explained how to rename the `game.gog` and `game.ins`, but did not mention that editing `game.ins`/`game.cue` was needed to mount it correctly.
Without this change, `WinCDEmu` (or any tool) shows an error without a clear explanation.
I also made a little more obvious that the list of files `BLOOD000.DEM-BLOOD003.DEM` is ... a list.
I was in a hurry to try the game and actually searched for `BLOOD000.DEM-BLOOD003.DEM` (which is a valid file name), before realizing it was meant as a list of files.
> Explain how to edit GOG's Blood game.ins

- source/exhumed/src/config.cpp
- source/exhumed/src/config.h
- source/exhumed/src/player.cpp
I noticed that auto run could only be changed via the cvar, so I added the Caps Lock key for it similar to other Build games.
> PCExhumed: Add Caps lock as the auto run toggle key

- source/rr/src/sbar.cpp
This change will use the the value of sbar.inv_amount[GET_SHIELD] when drawing armor/morale amount on the large status bar. This variable is already used by the mini-statusbar (ss == 4) when drawing the armor/morale amount.
> WW2GI: Fixed morale on large status bar

- source/exhumed/src/cd.cpp
- source/exhumed/src/exhumed.cpp
If the CD track file didn't exist the game loop kept calling playCDtrack every iteration without checking the return value. Now it only tries to play the track once if the file doesn't exist.
> PCExhumed: Don't try to open the CD track every frame

- source/exhumed/src/exhumed.cpp
- source/exhumed/src/menu.cpp
- source/exhumed/src/movie.cpp
- source/exhumed/src/player.cpp
- source/exhumed/src/ramses.cpp
The game kept hitting the texture cache, especially in the menus, so I added the missing waloff checks where necessary. I left DoLastLevelCinema and DoStatic as these do in-place animations on the Lobotomy laptop tile, so it needs to be cleared.
> PCExhumed: added waloff checks before tileLoad calls

- source/blood/src/network.cpp
If NETCODE_DISABLE was defined netResetToSinglePlayer never got called, which left the player number uninitialized.
> NBlood: Fix the NETCODE_DISABLE build

- source/blood/src/weapon.cpp
This is a bug in the original too.
Fixes the bug when cannot switch from spray can to anything else. While you are firing with spray can primary and meanwhile pressing another weapon's button, it will switch to nothing and nothing will be equipped. Need to select another weapon again to have a weapon in hand.
Also fixes the cases when Caleb puts away the lighter and raises it again (switching from TNT to spray or the other way while firing/throwing).
This PR does NOT fixes the case though when the player is using the next weapon and/or the previous weapon button. The code is too much of a mess (for me) to figure out what is happening. Maybe another time.
> Fix spray can weapon switching

- source/blood/src/weapon.cpp
Fix the issue when Caleb puts away the lighter and then pulls out again if the player is using the next/previous weapon button. No need to put away the lighter if spray/TNT is equipped and then TNT/spray will be equipped.
> Blood: Fix next/previous weapon switching in case of lighter

- source/exhumed/src/view.cpp
I noticed a rather funky looking crosshair sprite among the game's tiles, so I added it to the game. The position could probably be tweaked a bit, but it's more or less where it should be.
> PCExhumed: Add a crosshair

- source/exhumed/src/enginesubs.cpp
- source/exhumed/src/menu.cpp
- source/exhumed/src/sequence.cpp
I made some additions to the precache:
- animated tiles
- sequence pictures
- numbers for the countdown on the last level
This pretty much eliminates the tile loading during normal gameplay as long as everything fits in the cache.
> PCExhumed: improved precache

- source/blood/src/common_game.h
- source/blood/src/view.cpp
- source/blood/src/view.h
After the latest additions viewAddEffect failed to build without NOONE_EXTENSIONS. I also added ifdef guards at a couple of other places.
> NBlood: fix building without NOONE_EXTENSIONS

- source/blood/src/network.cpp
The gNetENetInit check in netDeinitialize was redundant, and it could cause some resource leak (the socket not getting closed) when the network game was aborted early on the "waiting for players" screen.
> NBlood: fix a resource leak in netDeinitialize

- source/blood/src/endgame.cpp
- source/blood/src/gamemenu.cpp
A few UI elements shrunk when the screen size as reduced, for example the images next to the save/load list, or the background of the "LEVEL STATS" text. This is a vanilla bug, but it's just a visual glitch on the UI, so I added the missing cstat flags where I saw this issue.
> NBlood: fix some UI elements affected by the screen size

- source/blood/src/actor.cpp
- source/blood/src/actor.h
- source/blood/src/ai.cpp
- source/blood/src/aiunicult.cpp
- source/blood/src/aiunicult.h
- source/blood/src/common_game.h
- source/blood/src/mirrors.cpp
- source/blood/src/nnexts.cpp
- source/blood/src/nnexts.h
Fix mirror (ROR) intialization so it won't crash if more than 1024 sectors used.
Fix random item generator so items that inherits TX ID won't send command at respawn.
Fix for things (400 - 433) that affected by modern physics so it won't return to vanilla physics after getting damage.
Fix kTeleportTarget so teleported sprites won't stuck in floors or ceilings.
Corpses won't gib as gargoyles anymore (gModernMap).
kModernCondition:
- remove bool comparison (condCmpb).
- remove no extra comparison (condCmpne).
- remove "else if" search at level start.
- add global (game) conditions type.
- add more conditions.
- make error report a bit more informative.
Add more options and damage effects for kModernSpriteDamager.
Add more options for kModernMissileGen and allow to spawn projectile on TX ID …
> Increase kMaxSuperXSprites from 128 to 512.

- source/blood/src/demo.cpp
I added the big endian swaps for the demo recording functions. I also fixed a small mistake in CDemo::SetupPlayback, where nMyConnectIndex was swapped twice potentially breaking multiplayer demos.
> NBlood: demo recording big endian fix

- source/blood/src/weapon.cpp
The underwater prev/next weapon fix copied the whole PLAYER struct onto the stack, but since only the curWeapon field is modified it's enough to back that one up. The WeaponFindNext, CheckAmmo, etc. functions leave the struct as is.
> Blood: Reduce WeaponProcess stack usage

- source/blood/src/mirrors.cpp
- source/blood/src/view.cpp
- source/blood/src/view.h
Even with gViewInterpolate off the game still performed interpolation at many places, just without any visible effect. I added gViewInterpolate checks so there are no unnecessary interpolation calculated in this case.
> Blood: add missing gViewInterpolate checks

- source/blood/src/nnexts.cpp
* check for ceilingstat used ceilingshade. Use of floorstat in the same block was correct.
* some sector check functions accessing walls.
I asked NoOne about these, he confirmed for both that it was not correct.
> - fixed two issues in condCheckMixed:

- source/exhumed/src/gun.cpp
This is an attempt to address issue #536. I tested this in both windowed and fullscreen, OpenGL and software. Attached are screenshots I took of the fix at various screen ratios.
This fix affects the regular and explosive death arms, I tested and screenshotted both types but for brevity only included one screenshot of regular death arms at the end. The rot/mummy and burn death arms appear fine since the art is intrinsically wider for those. Sample easy places to test rot/mummy in the wild is level 6 since they appear right at start, level 4 for burn death arm (go forward and turn left to lava).
The resolutions I tested for each screen ratio:
* 720x576     = 1.25
* 640x480     = 1.333333
* 720x480     = 1.5
* 1440x900   = 1.6
* 1024x600   = 1.706667
* 1920x1080 = 1.777778
1.25 screen ratio …
> PCExhumed: offset death arms for widescreen

- source/blood/src/controls.cpp
This fixes a bug I noticed in 2D map scroll mode. The forward, backward and strafe keys are supposed to move the view around only, but for forward and backward this actually moves the player as well. This bug does not appear to be in the base game (I ran One Unit Whole Blood in DosBox and the bug was not there).
This leads to incredibly annoying deaths (at edge of pit, open 2D map in scroll mode, scroll the map up, player walks forward off pit and dies).
It appears the bug occurs because we're writing the `forward` value to `gInput` instead of `input`, which defeats the later attempt to set `input` to zero in code specifically meant for scroll mode with 2D map open.
In `controls.cpp:[501-511]`:
```
if (!gViewMap.bFollowMode && gViewMode == 4)
{
...
input.q16turn = 0;
input.forward = 0; // …
```
> Blood: fix map scroll mode allows player forward movement

- source/blood/src/view.cpp
Meant to address issue #494. I compared the original DOS executable and confirmed it is indeed faster. This change does not change the overall duration of the effect (still about ~8 seconds), just the speed of it.
> Blood: fix delirium being twice as fast

- source/blood/src/controls.cpp
This fixes the map follow mode key toggling the follow mode setting outside the map (the map isn't open).
To reproduce:
1. Open 2D map.
2. Take note of follow mode setting.
3. Close 2D map.
4. Press follow mode setting key.
5. Open 2D map, notice the follow mode toggled while map was closed.
I was able to reproduce this in the base game as well (One Unit Whole Blood in DosBox). Can't think of a use case for why this should be allowed.
> Blood: fix map follow mode toggling outside map

- .gitignore
- source/blood/src/actor.cpp
An easy crash to trigger: Start a multiplayer game, and then end the game as host, while players are connected. netPlayerQuit sets up a post action, to delete sprite gPlayer[0]. This will end up happening after the demo is loaded that immediately tries to play, leading to a crash with an assertion failure for nSprite < kMaxSprites && sprite[nSprite].statnum < kMaxStatus or similar.
> BLOOD: clear gPost actions on actInit. Fixes some crashes.

- .gitignore
- source/blood/src/network.cpp
Currently, when the host ends a game, all the clients ShutDown, which is frustrating, and seems like a bug. (I thought they were crashing, but they just make it to the end of app_main). This PR sets the gQuitRequest to 2, so ProcessFrame's gRestartGame = gQuitRequest == 2 will set gRestartGame true.
Note, that without the [gPost fix](https://github.com/nukeykt/NBlood/pull/543) the client has post action sprite deletion problems, leading to a fairly quick crash during demo playback.
> BLOOD: fix host end game causing clients to ShutDown

- .gitignore
- source/blood/src/gamemenu.cpp
- source/blood/src/gamemenu.h
- source/blood/src/menu.cpp
- source/blood/src/menu.h
After a user map has been chosen the map that appears selected on the multiplayer config menu is never used again, even when the multiplayer menu is re-loaded for a New Game.  This makes it impossible to play the built in maps without restarting the executable.
The problem relates to StartNetGame and zUserMapName
Bstrncpy(gPacketStartGame.userMapName, zUserMapName, sizeof(gPacketStartGame.userMapName));
gPacketStartGame.userMap = gPacketStartGame.userMapName[0] != 0;
Nothing ever resets zUserMapName to an empty string. This means after any user map is chosen, gPacketStartGame.userMapName is always populated, and gPacketStartGame.userMap is always true.
I added a custom CGameMenuItem for the multiplayer menu title text with an Event method that clears zUserMapName on kMenuEventInit, which …
> BLOOD: fix last user map to not override menu map selected for new game

- source/blood/src/view.cpp
This PR will fix the fov bug where using the crystal ball powerup will force the default fov to be rendered for the player's current view. After rendering the crystal ball powerup window it'll reset to the current fov.
> Blood: Restore custom fov after rendering crystal ball powerup

- source/blood/src/fx.cpp
This PR fixes a rare edge case where it'll try to process sprites that are set to be free'd. This can occur when triggering too many blood sprites on a single tick, which this will cause the game to crash on next tick.
> Blood: Don't process already free'd fx sprites

- .gitignore
- source/blood/src/blood.cpp
- source/blood/src/levels.h
- source/blood/src/menu.cpp
- source/blood/src/network.h
- source/blood/src/player.cpp
Selecting the shared option means any player picking up a key gives it to all players. Zandronum has an option like this for Doom ([SV_ShareKeys](https://wiki.zandronum.com/DMFlags#ZaDMFlags)). Makes casual coop more fun when familiarity with the game varies in the group.
Thanks for NBlood. I've spent many hours playing the game solo and multiplayer with it.
> BLOOD: add option to share keys in multiplayer

- source/blood/src/view.cpp
This PR fixes a calculation offset error introduced by commit https://github.com/nukeykt/NBlood/commit/df4778e5130df5c11dc1d6bbd387b13498e9b356 when rendering a shadow above a ror floor. Instead of applying the secondary room position offset it'll use the height of the secondary room - this will correctly draw the Z offset required by the shadow.
> Blood: Fix shadow offset when rendering through room over room

- source/blood/src/view.cpp
This PR will scale burn time flames to output window width instead of fixed 4:3.
Example:
> Blood: Scale viewBurnTime() flames to window width

- source/blood/src/view.cpp
This fixes the current 'jittery' implementation for view height clamping when landing on surfaces/standing against ceiling. I've included videos to show a before/after, as well as a comparison with DOS.
https://user-images.githubusercontent.com/38839485/151655087-4aedd466-0fe0-4349-a69f-67ed5c603376.mp4
https://user-images.githubusercontent.com/38839485/151655126-09f18622-02e2-4ac7-8e82-4c56b0033c6f.mp4
https://user-images.githubusercontent.com/38839485/151654930-acda0070-5bda-4e56-a5ce-03af9f4aa94c.mp4
> Blood: Match view height clamping behavior to 1.21

- source/blood/src/menu.cpp
This PR will fix the incorrect difficulty setting listed when saving using game menu. SaveGame() will use UpdateSavedInfo() the same way as QuickSaveGame(), and update the gSaveGameOptions array with current session settings.
> Blood: Update gSaveGameOptions() on save game

- source/blood/src/blood.cpp
- source/blood/src/common_game.h
- source/blood/src/db.cpp
- source/blood/src/loadsave.cpp
This PR adds spriteext array to file save format, and fixes the maphacks getting desynced when loading saves (e.g: blood voxel pack). For example, loading a save to a different level will carry over the current level maphacks.
> Blood: Fix voxel maphacks desyncing when load save

- .gitignore
- source/blood/src/network.cpp
If a host or client had menus open when the host killed the game or the last player left, the menu would be the multiplayer menu, but it was no longer valid, and you had to press esc or End Game to get to a legit menu. Similar situation occurred if the host or all players quit while on the multiplayer game configuration menu before starting.
This deactivates the menu when the multiplayer game is reset to single player.  Very useful with [PR 544](https://github.com/nukeykt/NBlood/pull/544) and [PR 543](https://github.com/nukeykt/NBlood/pull/543) applied so client executables don't exit on host game end, and loading the demo doesn't crash.
> BLOOD: fix bad menu states by clearing after reset to single player

- source/build/include/mutex.h
- source/build/src/sdlayer.cpp
- source/build/src/sdlayer12.cpp
As there is still SDL 1.2 bindings currently present in the codebase this PR will enable the ability to target 1.2 again. While SDL1 has been given EoL status it is still useful for porting to older platforms such as the original Xbox or SGI systems.
> Fix SDL1.2 Target Support

- source/blood/src/sectorfx.cpp
This PR fixes ceiling panning direction when not using the relative flag as seen [in this issue](https://github.com/nukeykt/NBlood/issues/569).
> Blood: Fix ceiling panning angle

- source/blood/src/ai.cpp
This PR will set `aiInit()` to clear arrays `cumulDamage`, `gDudeSlope` and `gDudeExtra`. It will also restore the original vanilla behavior of leaving `pDudeExtra` uninitialized for edge case demo compatibility (spawn triggered enemies may inherit stats from previously free'd sprites).
> Blood: Clear AI Extra struct on aiInit()

- source/blood/src/view.cpp
This PR adds a check to prevent infinite ROR rendering as described in issue https://github.com/nukeykt/NBlood/issues/572. While does not not fix the core issue present in the polymer rendering pipeline it does stop the engine from softlocking when attempting to render infinite rooms.
> Blood: Limit ROR render to 32 times

- source/blood/src/blood.cpp
- source/blood/src/blood.h
- source/blood/src/credits.cpp
- source/blood/src/menu.cpp
- source/blood/src/network.cpp
This PR will dim the menu background while the menu is active/rendered, and makes reading options easier on the eyes. I've attached a video of this in action.
https://user-images.githubusercontent.com/38839485/155873427-3c417887-ddc2-4bb5-ad01-a4b223b1f50f.mp4
> Blood: Dim menu background while menu is active and add cryptic menu tile support

- source/blood/src/player.cpp
This PR fixes the view angle overflow issue when riding rotating platform sectors. For example the rotating platform on level E6M4 will cause the view to invert for a single frame due to an extreme interpolated overflow (eg: 2 -> 2023).
> Blood: Fix rotating platform view overflow

- source/blood/src/player.cpp
This PR will reset view/sway members for player initialization function `playerResetPosture()`. Currently if the player is jumping/moving during a level change trigger (such as E1M3) it'll retain the view bob/sway values for the next level, causing the player's view to 'jiggle' on spawn. This PR will initialize the view bob/sway values to 0 on level change and multiplayer spawn reset.
> Blood: Initialize viewbob members on player spawn

- source/blood/src/blood.cpp
- source/blood/src/network.cpp
- source/blood/src/network.h
This PR renames network.cpp function `sub_79760()` to the more descriptive `netResetState()`.
> Blood: Rename sub_79760() to netResetState()

- source/blood/src/aicult.cpp
This PR fixes the state bug for tesla cultists. By default when a tesla cultist goes into prone state they'll fire indefinitely and not break out of it. By setting the think function reference this will force the cultist to stand back up and continue functioning.
> Blood: Fix tesla cultist prone state

- source/blood/src/aispid.cpp
- source/blood/src/aiunicult.cpp
- source/blood/src/endgame.cpp
- source/blood/src/endgame.h
- source/blood/src/nnexts.cpp
- source/blood/src/triggers.cpp
This PR adds additional checks to the kill manager class. When adding an enemy it will apply the same check ruleset as CountTotalKills(). This fixes a off by one miscount when blacklisted sprite types are spawned via level trigger or respawned when level is using respawning enemies setting.
> Blood: Check enemy type when adding to enemy level count

- source/blood/src/actor.cpp
This PR changes `actSpawnDude()` to set the sprite property `inittype` for newly spawned dudes. The current behavior for spawn dudes will not set `inittype`, and the water cultist fix that relies on `inittype` will not work ([actor.cpp](https://github.com/nukeykt/NBlood/blob/1717c943be602cd8d4412ffafb6f632a5fd9efe4/source/blood/src/actor.cpp#L4868)).
I've also tested and confirmed that the PR does not change the respawning behavior for spawned enemies, as `actSpawnDude()` [sets the respawn variable to ignore](https://github.com/nukeykt/NBlood/blob/1717c943be602cd8d4412ffafb6f632a5fd9efe4/source/blood/src/actor.cpp#L6176) (this was a fix introduced in https://github.com/nukeykt/NBlood/commit/9e787bd8e00a9f826747a1414e4d3de88dc3c6f6).
> Blood: Set inittype on actSpawnDude()

- source/blood/src/aiunicult.cpp
This PR fixes an error introduced in commit https://github.com/nukeykt/NBlood/commit/08c35968b11f04f49d42477f29c3cbbd06ac4cd7.
Function `aiGenDudeInitSprite()` originally reset thinkTime for kDudeModernCustom, however I skimmed over this by accident when refactoring dudeExtra structure.
> Blood: Reset thinkTime for kDudeModernCustomDude initializing

- source/build/src/sdlayer.cpp
This PR fixes SDL 1 target for videoSetGamma(). Due to the non-bracketed if statement it would not properly set the gamma on first launch for SDL 1 builds.
> Fix videoSetGamma() for SDL1 target

- source/blood/src/menu.cpp
This PR calculates unique positions for each episode within the single player episode menu. It dynamically repositions each item so it is center weighted while the user map option is pushed down to the bottom. I've attached a gif of each possible layout from 1 episode to 6.
> Blood: Dynamically adjust episode menu items positions

- source/blood/src/credits.cpp
This PR adds additional memory checks to `credLogosDos()` as well as fixing the glitched palette bug that occurs when using an OpenGL renderer (polymost/polymer). For the second intro video playback it'll display one glitched frame. This issue was introduced in commit https://github.com/nukeykt/NBlood/commit/869d85ea10f69b037b51d5aeb5f0232a73379a5a.
> Blood: Fix intro playback video

- source/blood/src/credits.cpp
This PR fixes a bug introduced in commit https://github.com/nukeykt/NBlood/commit/5815e24a142d0adf92832c059889c52af5822c0a and adds a resolution check to video playback (0 pixel videos will safely exit).
> Blood: Fix possible memory leak in credPlaySmk()

- source/blood/src/menu.cpp
- source/blood/src/menu.h
- source/blood/src/osdcmd.cpp
This PR reimplements the PR https://github.com/nukeykt/NBlood/pull/562 as CVARs. Using OSD it'll automatically save and load the last used network port and address on load.
> Blood: Store net_address/net_port as CVARs

- source/blood/src/controls.cpp
This fixes 2D map mode not using forwards/backwards input while in scroll mode, which matches the same behavior as 1.21 DOS.
> Blood: Fix map scroll not using forward/backwards input

- source/blood/src/nnexts.cpp
This PR updates angold for modern level teleports to prevent turn interpolation for the current tick. The same fix was applied in commit https://github.com/nukeykt/NBlood/commit/6902fc73eaecfa2cd049970d8b69f8808aee897b for default teleporter triggers.
> Blood: Update player angold for modern kMarkerWarpDest types

- source/blood/src/actor.cpp
- source/blood/src/ai.cpp
This PR fixes a possible issue with spawned kDudeBurningCultist. As their inittype would be already set to kDudeBurningCultist, the current fix breaks as it'd constantly attempt to reset back to inittype which is kDudeBurningCultist. This resolves the issue by checking if the current sprite type is different to the inittype.
> Blood: Add self check for burning cultist fix

- source/blood/src/actor.cpp
- source/blood/src/ai.cpp
- source/blood/src/dude.h
- source/blood/src/messages.cpp
- source/blood/src/nnexts.cpp
- source/blood/src/player.cpp
- source/blood/src/player.h
This PR renames dude info struct member at70 to curDamage, which holds the currently shifted damage values for the game session, as well as using constants to access curDamage array.
> Blood: Use damage constants

- source/blood/src/mirrors.cpp
- source/blood/src/view.cpp
This PR changes the behavior used for viewing player sprites across ror sectors, such as when transitioning between ror. After comparing with 1.21 on a custom level it should appear to be more accurate now.
> Blood: Tweak ROR sprite cstat behavior

- source/blood/src/actor.cpp
This PR fixes the way no monsters mode is executed, and skips player sprites. Without this fix save games made without monsters will crash when attempting to load.
> Blood: Fix no monsters mode breaking on saving/loading game

- source/blood/src/_functio.h
- source/blood/src/blood.cpp
- source/blood/src/config.cpp
- source/blood/src/config.h
- source/blood/src/controls.cpp
- source/blood/src/credits.cpp
- source/blood/src/demo.cpp
- source/blood/src/endgame.cpp
- source/blood/src/gamemenu.cpp
- source/blood/src/menu.cpp
This is a very big PR, but it does work with the two controllers I've tried with, and from a friend's brief testing.
Using dynamic menu objects, the new joystick code will construct the button input pages, as well as a scaling axis menu. I used shadow warrior as my reference for implementing the joystick code, and added a feature to invert each axis. However no controller defaults are provided, as I was not too sure if this was a hold over from a wii port, or if they were broken.
Hooks have been added to game menu class, demo mode input handling and cutscenes/level end logic.
> Blood: Implemented joystick support

- source/blood/src/loadsave.cpp
This PR fixes a rare edge case where upon saving, then exiting a level (without demos present in folder), and loading the save will not restore music.
> Blood: Fix music not restoring on level load

- source/blood/src/blood.cpp
This PR changes co-op/team camera switching to switch to next player, and resolves crashes when a player has left the session.
> Blood: Improves coop camera switching

- source/blood/src/levels.cpp
This PR clears player input polling while cutscene is playing, so when level starts keyboard/mouse movement will be flushed.
> Blood: Clear all input on level start

- source/blood/src/messages.cpp
This PR only sets cheat message filtering for single player, and resets current active cheats on demo recording.
> Blood: Allow cheat phrases to be sent in multiplayer

- source/blood/src/sfx.cpp
This PR fixes a possible desync when using sfxPlay3DSoundCP(). If a client had sound turned off, this function will not call Random(), and thus would introduce a desync for that client. By using QRand this ensures no such desync will happen.
> Blood: Use network friendly QRand for sfxPlay3DSoundCP()

- source/blood/src/weapon.cpp
This PR fixes a bug introduced in commit https://github.com/nukeykt/NBlood/commit/6980e8b35527dfba1f994d97bef58505773a26ec.
When equipped with TNT, Remote TNT and Proxy TNT, attempting to switch to TNT via previous weapon will trigger the auto cycle TNT logic, and reselect Proxy TNT instead.
> Blood: Fix prev weap cycling bug for TNT

- source/blood/src/actor.cpp
- source/blood/src/aiunicult.cpp
- source/blood/src/eventq.cpp
- source/blood/src/nnexts.cpp
- source/blood/src/nnexts.h
- source/blood/src/nnextsif.cpp
- Do not allow to repeat action for all generators if state is 0
- Allow picking random incarnation for kModernDudeCustom
- Always kill all events if object is not part of event causer trigger sequence
- Fix incorrect argument for condition
- Stop dude patrol if there is no path markers to follow (no dassert)
- Fix potentially unsafe sprite removing from dynamic sprite lists
- Rewrite initialization
> gModernMap:

- source/blood/src/actor.cpp
- source/blood/src/aizombf.cpp
- source/blood/src/blood.cpp
- source/blood/src/common_game.h
- source/blood/src/loadsave.cpp
- source/blood/src/messages.cpp
- source/blood/src/network.cpp
- source/blood/src/nnexts.cpp
- source/blood/src/player.cpp
- source/blood/src/player.h
- source/blood/src/sfx.cpp
- source/blood/src/view.cpp
This PR defines a new set of kPack constants used by player inventory, as well as resolving the annoying reverb bug by reloading a save while reflective shots powerup is active. Other edits include giving crystal ball tile a constant define, and tweaking audio pitch adjustment for doppler calculation to match 1.21 behavior.
> Blood: Use pack constants and misc fixes

- source/blood/src/sound.cpp
This PR fixes the volume in the cutscenes #684  . The _int nVolume_ in _sndStartSample_ was being multiplied by 80, while it wasn't in _sndStartWavDisk_, leading to the cutscene volume being very low.
> [NBlood] Cutscene volume fix #684 

- source/blood/src/aiunicult.cpp
- source/blood/src/aiunicult.h
- source/blood/src/eventq.cpp
- source/blood/src/triggers.cpp
- source/blood/src/triggers.h
Most of the functions taking events don't poke into them, so they can be passed by const reference. This saves some work of copying them onto the stack for every call.
> Blood: Pass EVENTs by const reference when possible

- source/blood/src/gameutil.cpp
This is a mostly cosmetic change to make the hitsprite part of VectorScan similar to the hitwall one, which caches the tilesiz values in local variables.
> Blood: cache tilesiz values in local variables in VectorScan

- source/blood/src/resource.cpp
fixes #666  proper message of missing blood game file
> BLOOD:Resource Error handing when Blood Game resources file(s) not found

- source/blood/src/db.cpp
- source/blood/src/levels.cpp
- source/blood/src/loadsave.cpp
- source/blood/src/map2d.cpp
- source/blood/src/player.cpp
- source/blood/src/player.h
- source/blood/src/screen.cpp
- source/blood/src/view.cpp
This is a collection of tweaks/fixes for Blood. They include fixing the unused implementation of the detail sprite option, attempting to load cutscene files from movie directory as per install instructions, and renaming/redefining variables. Also included is improving the shadow position calculation as it'll now test for fake floor objects.
> Blood: Various tweaks

- source/blood/src/menu.cpp
This adds the option for [y-shearing](https://zdoom.org/wiki/Y-shearing) (r_yshearing) to the Polymost settings menu. Given that this is a togglable feature in the remaster, I thought it would make sense to also include this for the Polymost menu.
> Blood: Exposed polymost y-shearing option to menu

- source/blood/src/network.cpp
Properly resets gNetMode and other various net states when client is unable to connect to address.
> Blood: Fix game state on client time out

- source/blood/src/view.cpp
Fixes severe unplayable judder when playing multiplayer above 60fps. This will run every game tick instead of checking when player has moved/turn.
> Blood: Improve prediction logic for above 60fps

- source/blood/src/osdcmd.cpp
"Playing track #" seems more correct. No use in displaying strings for (-)"first", "second", nor "third" integers
> "Playing track number"

- source/sw/src/game.cpp
- source/sw/src/menus.cpp
- source/sw/src/menus.h
- source/sw/src/settings.h
- source/sw/src/sounds.cpp
- source/sw/src/swconfig.cpp
This PR adds a new option for shadow warrior, where it will use alternative settings for the reverb sound effect.
Comparison:
https://github.com/nukeykt/NBlood/assets/80724828/6c4513b9-66dd-4cb4-bbcf-f055c1506cec
https://github.com/nukeykt/NBlood/assets/80724828/5d7ff5e4-d778-4099-a06a-c207f194c057
> SW: Add new alt reverb option for sound menu

- source/blood/src/gamemenu.cpp
This PR unselects any actively edited CGameMenuItemZEdit items when leaving/entering a new menu.
> Blood: Deselect actively edited menu items on menu change

- source/blood/src/ai.cpp
This PR reverts a potential inaccuracy introduced in commit ed9b6f28fdfc6d3c00d0a5e412f8d30a79aa09b1. As the switch casement does not handle kDudeCerberusOneHead, an exception needs to be added so it is properly handled for `VanillaMode()`.
> Blood: Undo CanMove() inaccuracy

- source/blood/src/player.cpp
This PR reverts a inaccuracy introduced in commit 1efe584afcbb682550bbeab5b1caae469999994e. fragInfo array is used to store player kills by current player, while the commit changed it so all kills will only increase the same player index.
> Blood: Fix fragInfo inaccuracy

- source/blood/src/actor.cpp
- source/blood/src/blood.cpp
- source/blood/src/db.cpp
- source/blood/src/endgame.cpp
- source/blood/src/endgame.h
This PR changes the following:
* Rewrote kThingDroppedLifeLeech logic to look closer to original (functionally the same)
* Undo XSprite lT |= operation during map load
* Moved enemy filter for kill counter to CKillMgr class function
* Clear interpolations at start of game (fixes doors appearing open at multiplayer start)
> Various accuracy tweaks from Blood-RE

- source/blood/src/view.cpp
This PR tweaks the constant value view height clamping and calculation so it matches with Blood-RE. The commits that introduce the inaccuracies are 8ec01f926a74784a84de48d41a76bd64674d5fb5 and e72c9cb652814399d583220a16a6807620bcf541
> Blood: Match height clamping accuracy

- source/blood/src/actor.cpp
- source/blood/src/nnexts.cpp
- source/blood/src/seq.cpp
- source/blood/src/tile.cpp
- source/blood/src/tile.h
This PR addresses a possible issue when attempting to derive ceiling sector type from `tileGetSurfType()`.
When the sprite limit was increased for NBlood, `tileGetSurfType()`'s switch statement could no longer hit 0x6000. While no active code does use `tileGetSurfType()` to get ceiling surface type, it is now possible by supplying nType with the surface bitflag type.
> Blood: Allow tileGetSurfType() to return ceiling type if supplied nType bitflag

- source/blood/src/endgame.cpp
This PR fixes an inaccuracy introduced in commit bd03c40c57575c04015336dfcc83774c7b770f67. As vanilla mode **only** checks the enemy type at start, it should directly call AllowedType() and use AddCount(int) instead of AddCount(spritetype).
> Blood: Fix enemy count for vanilla mode

- source/blood/src/levels.cpp
This will only show the map filename instead of the full directory path for map title
> Blood: Remove directory path characters for levelGetTitle()

- source/blood/src/controls.cpp
Add autorun/run functionality for controller input. This should have no effect on non-autorun keyboard input while controller is plugged in - regardless it should be tested before merging (compare in_joystick 0 and 1 walking speed).
> Blood: Implement autorun/run functionality for controller input

- source/blood/src/_functio.h
- source/blood/src/blood.cpp
- source/blood/src/function.h
This PR will add two new buttons to the list of inputs, and default bind F6 and F9 to quick save and quick load, thus allowing controller players to use a function that is semi-required to enjoy Blood on difficulties above lightly broiled. It will also leave the F6 and F9 hardcoded as their respective quick save and quick load keys, so users updating NBlood won't suddenly be unable to quick save and quick load.
> Blood: Expose quick save/load functionality as buttons

- source/blood/src/weapon.cpp
This fixes an erroneous weapon state while equipped with akimbo mode. The akimbo states it fixes are:
* Firing the napalm launcher with 4-2 ammo
* Lowering QAV for shotgun and napalm launcher
> Blood: Fix firing state with akimbo mode for shotgun/napalm launcher

- source/audiolib/src/driver_sf2.cpp
- source/audiolib/src/tsf.h
- source/blood/src/messages.cpp
This PR adds nearest neighbor and cubic interpolation for soundfont playback, and improves the overall sound quality for low frequency notes.
The default interpolation method is set to cubic, however the option for selecting which interpolation method (NEAREST/LINEAR/CUBIC) can be added in the future with the new interpolatemode option argument.
> Add cubic interpolation for SF2 playback

- source/blood/src/actor.cpp
- source/blood/src/ai.cpp
- source/blood/src/callback.cpp
- source/blood/src/db.h
- source/blood/src/demo.cpp
- source/blood/src/mirrors.cpp
- source/blood/src/network.cpp
- source/blood/src/nnexts.cpp
- source/blood/src/player.cpp
- source/blood/src/view.cpp
- source/blood/src/weapon.cpp
> Blood: Use VIEWPOS enum and other various tweaks

- source/blood/src/menu.cpp
- source/blood/src/messages.cpp
This tweaks a variable name for the new custom menu, and shuffles line order within `LevelWarpAndRecord()`.
> Blood: Minor tweaks

- source/audiolib/src/tsf.h
This PR incorporates this upstream PR which has yet to be imported.
https://github.com/schellingb/TinySoundFont/pull/85
> TSFLib: Convert attenuation from centibels to decibels

- source/blood/src/blood.cpp
This fixes an issue where the hotkey for quicksave/quickload is triggered twice.
> Blood: Clear quicksave/quickload keybinds on F6/F9

- source/blood/src/view.cpp
- source/sw/src/sounds.cpp
This forces the third person sprite for the current player to use the predicted fake movement position for multiplayer.
> Blood: Improve third person sprite prediction for network play

- source/audiolib/src/flac.cpp
- source/blood/src/blood.cpp
This PR resolves an issue compiling on Linux with FLAC support enabled, as suggested in #665
> Use latest library headers for FLAC

- source/blood/src/weapon.cpp
This PR resets the weapon state when switching weapon (this is based off of [BloodGDX's logic](https://gitlab.com/m210/BloodGDX/-/blob/942c07f31c61b6b2402ec393596ac414f683bc74/core/src/ru/m210projects/Blood/Weapon.java#L1552-1555)), and fixes issue #799
> Blood: Reset weapon state when switching weapons

- source/blood/src/weapon.cpp
This PR fixes this bug reported here. https://github.com/nukeykt/NBlood/issues/199
When a player drops below 4 shells while the akimbo powerup is active, they'll be locked to a single shotgun regardless if they pick up more ammo. This fix will force a ammo check for the shotgun upon every reload, and will switch back to two shotguns if the akimbo powerup is still active.
> Blood: Fix shotgun bug with akimbo

- source/blood/src/view.cpp
This PR fixes an oversight calculation error introduced in commit 8658502070088cfbcc1a6b0729c8283086557ab8. When the view window is set to a small size, text will overlay the frag score counter HUD element, as it was not properly using the right calculation for the element.
> Blood: Fix error calculating frag HUD element for message height offset

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
The following games can be build and debugged within VS Code with this change:
- Rednukem
- NBlood
- PCExhumed
- ETekwar
- EWitchaven
Removed configuration for:
- EDuke32
- Mapster32
- VoidSW
- Wangulator
- EKenbuild
- EKenBuild-Editor
Also removed .gitignore for .vscode folder.
Commits are signed now.
> Added games to VS Code build & debug configuration

- source/blood/src/blood.cpp
- source/blood/src/blood.h
This PR optimizes `VanillaMode()` by rewriting it as an inlined function.
While LTO does effectively turn this into an inlined function, it will not for non-LTO compiles. This will help performance for compiles for lower powered devices, as `VanillaMode()` is called upon many times per main loop.
> Blood: Inline VanillaMode()

- source/blood/src/blood.cpp
- source/blood/src/loadsave.cpp
- source/blood/src/menu.cpp
- source/blood/src/view.cpp
This PR fixes issue #506 as well as fixing the bo~~a~~rders for classic renderer while powerups and stats are being drawn.
Additionally, this PR also fulfills #818
Fixes #506
Fixes #818
> Blood: Update logic used to redraw screen border and add new -s CLI argument

- source/blood/src/aibat.cpp
This PR adds a sanity check for the bat attack state when loading/saving files.
This is referenced off of an earlier fix made to bone eels (00107feb0c310ce24a3d022bde3be18dc2d342a8) and the same fix is applied to bats.
This PR also fixes the report issues #444 #607 and #454
Fixes #444
Fixes #607
Fixes #454
> Blood: workaround for bat attack state

- source/blood/src/asound.cpp
Based on comparing to the DOS version, it appears that the original Apogee Sound System would not play muted channels, until they had been unmuted (likely a form of optimization). This means any ambient sound effects would remain 'paused' until their volume was set to a non-zero value.
This PR emulates this original behavior with the newer audio library which does not have the same optimization.
Fixes #393
> Blood: Pause muted ambient channel until unmuted

- source/blood/src/config.cpp
- source/blood/src/osdcmd.cpp
This PR forces `gSetup.usejoystick` and `gSetup.usemouse` to be loaded from `nblood.cfg` instead of `nblood_cvars.cfg`, as the OSD subsystem is initialized after the start window has closed, and thus the use mouse/joystick settings are never loaded.
Fixes #794
> Blood: Load mouse/joystick values from non-OSD cfg

- source/blood/src/blood.cpp
This PR adds two prone type checks to the PrecacheDude() dude function when loading maps, so they are cached like the non-prone cultist types.
> Blood: pre-cache SEQs for prone cultist enemy types

- source/blood/src/db.cpp
This PR adds a missing header to define `VanillaMode()` which is now part of `blood.h` instead of `globals.h`.
> Blood: Fix NOONE_EXTENSIONS=0 build

- source/blood/src/_functio.h
- source/blood/src/config.cpp
This PR restores the controller defaults that were removed in PR #642 for Blood. It uses a xbox controller as the basis for the default mappings.
> Blood: Add controller defaults

- source/blood/src/menu.cpp
- source/blood/src/view.cpp
This PR adds the option to only allow stats to appear on the automap.
> Blood: Add option to show stats on automap only

- source/blood/src/controls.cpp
This PR fixes the crouch toggle implementation for underwater movement, originally introduced in #783
Fixes a bug where it was not possible to swim downwards and required the use of the default crouch bind.
> Blood: Fix crouch toggle logic for underwater movement

- source/blood/src/config.cpp
This PR fixes an incorrectly set string limit for the player name variable being loaded from the cfg file, as it would always cut the string length to 10 characters, despite the player name menu item and player struct member supporting names up to 16 characters long.
> Blood: Increase player name limit to 16 characters

- source/blood/src/loadsave.cpp
This PR fixes an bug that occurs when loading a mod folder and searching for existing local saves.
It should now properly report saves found in the mod folder instead of the default location.
> Blood: Fix loading save info from mod directory

- source/blood/src/config.cpp
- source/blood/src/config.h
- source/blood/src/controls.cpp
- source/blood/src/menu.cpp
- source/blood/src/osdcmd.cpp
This PR adds the ability to change turn speed and turn off turn speed acceleration for Blood much like BloodGDX.
> Blood: Add turn speed slider for keyboard input

- GNUmakefile
- source/blood/src/actor.cpp
- source/blood/src/ai.cpp
- source/blood/src/ai.h
- source/blood/src/callback.cpp
This PR fixes a common issue of channels being cut out upon an enemy's death, and resolves an original game bug of cultist alerts continuing to play on death.
When an enemy is killed by a hitscan weapon such as the shotgun or tommy gun, it'll spawn a spurt of blood that has a random chance of triggering a splattering sfx upon hitting the ground - and cutting off the still ongoing enemy death sfx. This PR will set the sound effect trigger to only play if the channel is available, instead of cutting off the voice.
For cultists, when they are killed at point blank range with the shotgun, it'll trigger the activate callout sfx, then the death sfx in the same tick. This PR resolves this by setting all cultists to use their own unique channel slot for callouts, so they are cut off upon dying or …
> Blood: Fix enemy death sfx getting cut and fix cultist sfx not getting cut on death

- source/blood/src/actor.cpp
- source/blood/src/player.cpp
When akimbo is activated/deactivated, it will force the player to lower their weapons and reequip the current weapon.
This PR changes the akimbo behavior when holding the weapons that do not have an akimbo state (such as the ptichfork, TNT, spray can, voodoo doll, etc), so they do not force a weapon reequip.
> Blood: Don't reequip single handed weapons for akimbo powerup

- source/blood/src/actor.cpp
- source/blood/src/sfx.cpp
This PR fixes an oversight introduced in #854
I fixed it by giving cultist death callout sfx their own unique channel, and created a new bitflag (8) for sfx so it won't assign a tracking pointer to the sprite. This means it'll behave exactly like a channel-less sfx but won't be free'd until the sfx has finished playing.
Fixes #804
> Blood: Assign unique channel to cultist death cry

- source/blood/src/actor.cpp
- source/blood/src/blood.cpp
- source/blood/src/gamemenu.cpp
- source/blood/src/globals.cpp
- source/blood/src/globals.h
- source/blood/src/loadsave.cpp
- source/blood/src/mapedit.cpp
- source/blood/src/network.cpp
- source/blood/src/triggers.cpp
- source/blood/src/view.cpp
This PR will automatically give saves with blank names a valid string, based off of the save file map name.
Additionally, this PR will also restore the original quantized, blocky movement for weapon sway when vanilla mode is enabled, and optimizes the widescreen scaling for burn flame HUD rendering.
> Blood: Use map name for blank save game names, optimize viewBurnTime() and use original calc for vanilla weapon sway

- source/blood/src/weapon.cpp
This PR restores sprite interpolation for HUD weapon drawing.
Fixes https://github.com/nukeykt/NBlood/issues/499
> Blood: Fix weapon interpolation

- source/blood/src/mirrors.cpp
- source/blood/src/mirrors.h
- source/blood/src/view.cpp
This PR fixes crashes when attempting to render shadows in mirror sectors, and improves the overall robustness for testing fake floors below the object casting a shadow. I've tested this with Bloodlines E1M1's fake floor, and Blood E2M5's fake floor in the house lobby.
The below pic would crash with the currently released build, this has since been fixed.
> Blood: Fix shadows crashing when rendered in mirrors

- source/blood/src/aihand.cpp
- source/blood/src/blood.cpp
- source/blood/src/player.cpp
- source/blood/src/view.cpp
This PR fixes hand enemies not working in multiplayer.
Fixes #830
> Blood: Add multiplayer support for hand enemies

- source/blood/src/menu.cpp
This PR allows users to insert a controller after menu initialization.
> Blood: Support controllers inserted after menu initialization

- source/blood/src/blood.cpp
This PR adds tile caching for baby spider types when a mother spider is present in the level. This should fix invalid sprites when these enemies are ignited on fire such as on E4M2.
> Blood: Precache baby spiders for mother spider

- source/blood/src/menu.cpp
This PR uses constant kMaxLevels for zLevelNames array size, aiding in users who wish to change the maximum supported levels for NBlood.
> Blood: Use kMaxLevels for zLevelNames

- source/blood/src/gamemenu.cpp
- source/blood/src/gamemenu.h
This PR adds a check to the keyboard control settings, so the user is alerted when a conflicting key has been bound.
Example, backspace has been bound to crouch toggle, while it already used for turn around function.
> Blood: Alert to user if new key bind conflicts with existing key function

- source/blood/src/weapon.cpp
This PR fixes the invalid frame triggering when firing the shotgun with the akimbo powerup.
It is based off of BloodGDX's fix https://gitlab.com/m210/BloodGDX/-/commit/3cb4a17b2b987e8c08a50085042f06ad724ec4b3
Before
https://github.com/user-attachments/assets/dba44fbb-57e5-4f7b-9798-36db86dbe88e
After
https://github.com/user-attachments/assets/ab4b5689-5a19-4658-a2ee-d2de1639c0c5
> Blood: Fix shotgun akimbo frame bug

- source/blood/src/view.h
- source/blood/src/warp.cpp
This PR restores the interpolated state for sprites that are transitioned through room-over-room links, much like how 71519e9edf7fa3a9fbecf5f097fee29a26b2da94 did for player view momentum.
Before
https://github.com/user-attachments/assets/58ec8d69-fa88-4d68-99bb-eea34401a747
After
https://github.com/user-attachments/assets/4414fbf8-b067-43ee-87e8-09fec1d6d461
> Blood: Fix interpolated sprite offsets for room over room transitions

- source/blood/src/actor.cpp
- source/blood/src/nnexts.cpp
- source/blood/src/player.cpp
- source/blood/src/sfx.cpp
- source/blood/src/sfx.h
- source/blood/src/triggers.cpp
This PR changes/fixes the following
* Player listening velocity breaking doppler on respawn/map start
* Doppler calculation breaking when teleporting across great distances
* Use `kEarDist` constant for doppler calculation
* Define internal sfx.cpp listening position variables as static
Before
https://github.com/user-attachments/assets/47feb2f2-1b95-4572-b49e-849e9e12a231
https://github.com/user-attachments/assets/76943dde-8f47-4009-8fa7-b75e89cedb38
After
https://github.com/user-attachments/assets/e6071e3e-11b0-4313-a21b-474768cd41ca
> Blood: Reset player sfx velocity on spawn/teleport/ror transition, and refactor sfxUpdate3DSounds()

- source/blood/src/menu.cpp
This PR adds a graphical detail slider/voxel toggle to the options menu.
> Blood: Add detail slider and voxel toggle to options

- source/blood/src/aicdud.cpp
- source/blood/src/common_game.h
- source/blood/src/eventq.cpp
- source/blood/src/globals.cpp
- source/blood/src/levels.h
- source/blood/src/loadsave.cpp
- source/blood/src/nnexts.cpp
That mod (I'll call it WLB from here on) ships a modified version of NBlood.
The author released the source of that as a .7z archive on Google Drive: https://drive.google.com/drive/folders/1q8qsPCYSRnZGCoPC602jRzjLPQO7a7Wb
According to the WLB Readme.txt, the most important change was increasing the allowed number of maps from 16 to 45 (because that mod has a lot of maps!), but there are several other changes as well.
In the current form, this PR does *not* make NBlood compatible with WLB, but it has several fixes and improvements I originally made when playing (and debugging) WLB.
Further down there are comments about other changes NBlood could do to better support mods like WLB without the mod having to fork NBlood.
> Several improvements related to Blood: What Lies Beneath

- source/blood/src/blood.cpp
- source/blood/src/player.cpp
This PR fixes an enemy count bug that was introduced by #864.
When hand enemies attach to players their sprite is removed, until the player is able to successfully throw the enemy off by tapping the use key. However if the player dies, the enemy will never be dropped and is forever removed. Normally this would never cause an issue for single player, but with #864 it exposes an issue with the enemy count.
Because multiplayer allows player respawns, the total enemies will become broken if a player dies to an hand enemy and will render the match impossible to kill every enemy.
By forcing the hand enemy to 'drop' on player death for multiplayer, it will fix the total enemy count breaking.
> Blood: Drop hand enemy after killing player for multiplayer

- source/blood/src/player.cpp
This PR fixes a out of bounds read bug for CalcNonSpriteChecksum().
> Blood: Fix out of bounds array check for CalcNonSpriteChecksum()

- source/blood/src/barf.cpp
- source/blood/src/common_game.h
- source/blood/src/db.cpp
- source/blood/src/loadsave.cpp
This PR resolves the warnings for db.cpp, properly fixes an oversight when saving gSongId/gSkyCount variables and bumps the save version up to 107.
> Blood: Save gSongId/gSkyCount variables and use constants for map decrypting

- source/blood/src/view.cpp
This PR restores the original fix that commit 0d7bcf0462d5d899b7b14edd6a8c8be9609c22cd resolves while also fixing an edge case for non-dude sprites and overall being clearer to understand.
Fixes the vanilla bug where a floor pal 0 overrides sprites that purposefully use a non 0 palette (such as tommy cultists in E3M2).
Addresses issue #385 correctly.
> Blood: Don't override sprite palette for floorpal 0 sectors

- source/blood/src/menu.cpp
- source/blood/src/osdcmd.cpp
- source/blood/src/weapon.cpp
Smaller enemies such as the hands, rats and fish appear to be designed in mind for autoaim as it's incredibly difficult to hit them precisely when autoaim is turned off.
This PR adds a new autoaim setting to allow players to always have autoaim set for the pitchfork weapon, so players who prefer not to use autoaim can have it only applied for the pitchfork.
> Blood: Add 'pitchfork only' autoaim option

- GNUmakefile
- platform/Windows/nblood.vcxproj
- platform/Windows/nblood.vcxproj.filters
- source/blood/src/actor.cpp
- source/blood/src/common_game.h
- source/blood/src/gamemenu.cpp
- source/blood/src/inifile.cpp
- source/blood/src/inifile.h
- source/blood/src/nnextcdud.cpp
- source/blood/src/nnextcitem.cpp
- source/blood/src/nnextcitem.h
- source/blood/src/nnexts.h
- source/blood/src/nnextstr.cpp
- source/blood/src/nnextstr.h
- source/blood/src/player.cpp
- source/blood/src/player.h
- source/blood/src/view.cpp
Replace IniFile class (inifile.cpp, inifile.h)
> Add custom item system (nnextcitem.cpp, nnextcitem.h)

- source/blood/src/credits.cpp
This addresses a bug if the user has set palette emulation to false for polymost, and tries to render FMV.
> Blood: Reset palette colors on cutscene trigger

- source/blood/src/actor.cpp
- source/blood/src/config.cpp
- source/blood/src/config.h
- source/blood/src/controls.cpp
- source/blood/src/controls.h
- source/blood/src/globals.h
- source/blood/src/menu.cpp
- source/blood/src/osdcmd.cpp
- source/blood/src/player.cpp
- source/blood/src/weapon.cpp
This PR adds two additional miscellaneous functions for joystick support (both off by default), and a new joystick options menu.
* Center view upon landing (only for joystick)
* Rumble support
> Blood: Joystick rumble support

- source/blood/src/actor.cpp
This PR adds additional checks for OOB read for the life leech, will forcefully set to 512 proxy dist for the life leech if an invalid owner is detected (further adjusts edits made by 837e2376ae5c45bce810b6abff7744a1c38f25e8)
> Blood: Always set life leech proxyDist to 512 for invalid owner

- source/blood/src/view.cpp
This PR addresses #907 by adding the current remaining air supply of the diving suit while underwater to the powerup HUD display.
Fixes #907
> Blood: Add diving suit to powerup HUD feature

- source/blood/src/controls.cpp
- source/blood/src/credits.cpp
This PR fixes the weird intro skip for the start of the game, and adds an additional `KB_FlushKeyboardQueueScans()` clear to `ctrlClearAllInput()` much like how `CGameMenuItemKeyList::Scan()` does.
> Blood: Properly flush input for cutscenes

- source/blood/src/sfx.cpp
This PR adjusts the pitch clamp to 1000, so mappers may be able to use ultra low pitched audio
> Blood: Adjust pitch clamp to 1000

- source/blood/src/blood.cpp
This PR improves mouse aiming and input polling responsiveness by placing it at the top of the main loop, which will poll inputs regardless if a frame is ready to be drawn or not - instead of only polling input when a frame is being drawn.
> Blood: Move input polling at start of game loop

- source/blood/src/blood.cpp
This PR reduces uselessly polling input twice while the game is active.
For example, if the player bound key `\` to noclip, it would toggle it twice in the same frame because of the double input polling.
By forcing it to only read once while the game is active, it'll fix this issue.
> Blood: Don't poll input twice for same frame while game is active

- source/blood/src/map2d.cpp
This PR fixes a bug where the 2D map view does not scale to the output window size.
Below is an example of the issue in action. This is set to maximum map zoom.
> Blood: Scale 2D map view to output resolution
